# Generated by Django 2.1.2 on 2018-11-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
